(define (problem swerve)
  (:domain racetrack)
  (:objects w1 w2 w3 w4 w5 w6 w7 w8 w9 - wall)
  (:init (= (x) 3)
         (= (y) 3)
         (= (vx) 0)
         (= (vy) 0)
         (= (ax w1) 0)
         (= (ay w1) 0)
         (= (bx w1) 24)
         (= (by w1) 0)
         (= (ax w2) 24)
         (= (ay w2) 0)
         (= (bx w2) 24)
         (= (by w2) 24)
         (= (ax w3) 0)
         (= (ay w3) 24)
         (= (bx w3) 24)
         (= (by w3) 24)
         (= (ax w4) 0)
         (= (ay w4) 0)
         (= (bx w4) 0)
         (= (by w4) 24)
         (= (ax w5) 6)
         (= (ay w5) 0)
         (= (bx w5) 6)
         (= (by w5) 18)
         (= (ax w6) 6)
         (= (ay w6) 18)
         (= (bx w6) 18)
         (= (by w6) 18)
         (= (ax w7) 18)
         (= (ay w7) 6)
         (= (bx w7) 18)
         (= (by w7) 18)
         (= (ax w8) 12)
         (= (ay w8) 6)
         (= (bx w8) 18)
         (= (by w8) 6)
         (= (ax w9) 12)
         (= (ay w9) 6)
         (= (bx w9) 12)
         (= (by w9) 12)
  )
  (:goal (and (>= (x) 15)
         (<= (x) 17)
         (= (y) 10)
         (= (vx) 0)
         (= (vy) 0)
)))
