(define (problem swerve)
  (:domain racetrack)
  (:objects w1 w2 w3 w4 w5 w6 w7 w8 w9 - wall)
  (:init (= (x) 3)
         (= (y) 1)
         (= (vx) 0)
         (= (vy) 0)
         (= (ax w1) 0)
         (= (ay w1) 0)
         (= (bx w1) 8)
         (= (by w1) 0)
         (= (ax w2) 8)
         (= (ay w2) 0)
         (= (bx w2) 8)
         (= (by w2) 8)
         (= (ax w3) 0)
         (= (ay w3) 8)
         (= (bx w3) 8)
         (= (by w3) 8)
         (= (ax w4) 0)
         (= (ay w4) 0)
         (= (bx w4) 0)
         (= (by w4) 8)
         (= (ax w5) 4)
         (= (ay w5) 0)
         (= (bx w5) 4)
         (= (by w5) 2)
         (= (ax w6) 3)
         (= (ay w6) 2)
         (= (bx w6) 5)
         (= (by w6) 2)
         (= (ax w7) 5)
         (= (ay w7) 2)
         (= (bx w7) 5)
         (= (by w7) 6)
         (= (ax w8) 3)
         (= (ay w8) 6)
         (= (bx w8) 5)
         (= (by w8) 6)
         (= (ax w9) 3)
         (= (ay w9) 2)
         (= (bx w9) 3)
         (= (by w9) 6)
  )
  (:goal (and (>= (x) 5)
         (<= (x) 6)
         (= (y) 1)
         (= (vx) 0)
         (= (vy) 0)
)))
