(define (problem swerve)
  (:domain racetrack)
  (:objects w1 w2 w3 w4 w5 w6 w7 w8 w9 - wall)
  (:init (= (x) 12)
         (= (y) 4)
         (= (vx) 0)
         (= (vy) 0)
         (= (ax w1) 0)
         (= (ay w1) 0)
         (= (bx w1) 32)
         (= (by w1) 0)
         (= (ax w2) 32)
         (= (ay w2) 0)
         (= (bx w2) 32)
         (= (by w2) 32)
         (= (ax w3) 0)
         (= (ay w3) 32)
         (= (bx w3) 32)
         (= (by w3) 32)
         (= (ax w4) 0)
         (= (ay w4) 0)
         (= (bx w4) 0)
         (= (by w4) 32)
         (= (ax w5) 16)
         (= (ay w5) 0)
         (= (bx w5) 16)
         (= (by w5) 8)
         (= (ax w6) 12)
         (= (ay w6) 8)
         (= (bx w6) 20)
         (= (by w6) 8)
         (= (ax w7) 20)
         (= (ay w7) 8)
         (= (bx w7) 20)
         (= (by w7) 24)
         (= (ax w8) 12)
         (= (ay w8) 24)
         (= (bx w8) 20)
         (= (by w8) 24)
         (= (ax w9) 12)
         (= (ay w9) 8)
         (= (bx w9) 12)
         (= (by w9) 24)
  )
  (:goal (and (>= (x) 20)
         (<= (x) 24)
         (= (y) 4)
         (= (vx) 0)
         (= (vy) 0)
)))
