(define (problem swerve)
  (:domain racetrack)
  (:objects w1 w2 w3 w4 - wall)
  (:init (= (x) 3)
         (= (y) 40)
         (= (vx) 0)
         (= (vy) 0)
         (= (ax w1) 0)
         (= (ay w1) 0)
         (= (bx w1) 50)
         (= (by w1) 0)
         (= (ax w2) 50)
         (= (ay w2) 0)
         (= (bx w2) 50)
         (= (by w2) 50)
         (= (ax w3) 0)
         (= (ay w3) 50)
         (= (bx w3) 50)
         (= (by w3) 50)
         (= (ax w4) 0)
         (= (ay w4) 0)
         (= (bx w4) 0)
         (= (by w4) 50)
  )
  (:goal (and (= (x) 30)
         (>= (y) 10)
         (<= (y) 30)
         (= (vx) 0)
         (= (vy) 0)
)))
